console.log("Begin program");
var noOfQuestions = 5;
var questionsLeft = ' [' + noOfQuestions + ' questions left]';
var favoriteAnimal1 = prompt('Please enter your favorite animal' + questionsLeft);
noOfQuestions -= 1;
questionsLeft = ' [' + noOfQuestions + ' questions left]';
var firstName1 = prompt('Please enter a first name' + questionsLeft);
noOfQuestions -= 1;
questionsLeft = ' [' + noOfQuestions + ' questions left]';
var adjective1 = prompt('Now enter an adjective' + questionsLeft);
noOfQuestions -= 1;
questionsLeft = ' [' + noOfQuestions + ' questions left]';
var favoriteDish = prompt("What's your favorite dish?" + questionsLeft);
noOfQuestions -= 1;
questionsLeft = ' [' + noOfQuestions + ' questions left]';
var worstPain = prompt("What's the worst pain you know?" + questionsLeft);
alert('All done. Ready for the your story?');
var story = '<p>There once was a ' + adjective1 + ' ' + favoriteAnimal1 + ', named ' + firstName1 + '. ' + firstName1 + ' loved ' + favoriteDish;
story += ', but one day ' + firstName1 + ' ate way too much ' + favoriteDish + ' and got a ' + adjective1 + ' ' + worstPain + '. The End!';
document.write(story);
console.log("End program. Hope you enjoyed it!");
